### ISSUE TITLE
The morphing grid of the sample code flickers...

### ISSUE THREAD

**Issue by Drachenbauer** [morpho-matters/morpholib#1] opened 2022-11-06 00:08 UTC
I installed pycairo and morpholib and did a run of the test-code.
i see the morphing grid, but the whoole thing flickers in horizontal lines...
So i now think, what if my own animated calculations also flicker like this?

**Comment by morpho-matters** [comment] 2022-11-06 20:17
Could you provide the OS you're on and which version of Python you're using? That's always some helpful info.

In any case, to see if the problem is merely with the animation previewer, try running the following script in an empty directory:
```python
import morpholib as mo
mo.importAll()

grid = mo.grid.mathgrid()
grid = mo.Actor(grid)
grid.newendkey(4, grid.first().fimage(lambda s: s**2/10))

mation = mo.Animation(grid)
mation.export("./test.png")
```
It should output 5 PNG images to the current working directory. Check if those images have any flickering artifacts. If they look okay, then the problem is likely just with the previewer and so the animation should look fine when rendered to MP4 or GIF. If you already have FFMPEG already installed, you can try running the following script to see if the outputted MP4 video is okay:
```python
import morpholib as mo
mo.importAll()

grid = mo.grid.mathgrid()
grid = mo.Actor(grid)
grid.newendkey(30, grid.first().fimage(lambda s: s**2/10))

mation = mo.Animation(grid)
mation.endDelay(60)
mation.export("./test.mp4")
```
Another thing to test is to run the original sample animation `morpho.sample.play()` and try pausing the animation in the middle by clicking inside the animation window while it's playing. If it looks fine at a frozen frame and only has the flickering effect when in motion, that further suggests the issue is with the previewer and perhaps also how your machine handles graphics.

Let me know what you find!

**Comment by Drachenbauer** [comment] 2022-11-13 13:45
My system: nitro 5 laptop, windows 11, python 3.11, morpholib 0.5.1

i added your export lines to a code, that i made, that creates a yellow kite-shape.

The png-export looks normal:
![test](https://user-images.githubusercontent.com/47259059/201524414-dba11b5b-37b7-40d5-8b26-ff98745b29d2.png)

A screenshot from the run-window looks green stripe flickered:
![Flicker 2](https://user-images.githubusercontent.com/47259059/201524815-1ba0f5bc-3035-4159-b979-e4988bb43f70.png)

and the mp4 export gives this error:

> Traceback (most recent call last):
  File "D:\Mods\Python\venv\Math_Animations\main.py", line 22, in <module>
    animation.export("./test.mp4")
  File "C:\Users\maxi_\AppData\Roaming\Python\Python311\site-packages\morpholib\anim.py", line 2887, in export
    sp.call(cmd)
  File "D:\Program Files\Python311\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Python311\Lib\subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\Program Files\Python311\Lib\subprocess.py", line 1491, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

clicking in the test-animation stops the movement but the green stripes stay, just appear static then

**Comment by morpho-matters** [comment] 2022-11-14 01:24
All right, based on what you've said, it looks like the problem is only with the previewer and not with the exporter. The tool Morpho uses for animation previewing is pyglet, and after a little Googling, it looks like this might be a problem with certain graphics cards/drivers, and perhaps solvable by updating the driver. I'd recommend you take a look at [this thread](https://github.com/psychopy/psychopy/issues/3228) for more info.

As for the export error, have you installed [FFmpeg](https://ffmpeg.org/download.html) onto your machine and added it to your PATH environment variable? If you're not sure, try typing `ffmpeg` in a terminal window. If it throws an error saying something like "ffmpeg is not recognized", then you don't have it part of your PATH. However, if you have the ffmpeg.exe executable somewhere on your machine but you don't want to add it to your PATH, Morpho can still use it if you add the following line after the import statement:
```python
import morpholib as morpho
morpho.anim.ffmpeg = "your/path/to/ffmpeg.exe"
```

**Comment by Drachenbauer** [comment] 2022-11-14 17:14
I downloaded ffmpeg.exe and added it to my project-path.
now i could export a mp4 video and it looks alright.
only a run preview window shows that flicker.

**Comment by Drachenbauer** [comment] 2022-11-14 17:42
I downloaded ffmpeg.exe and added it to my project-path.
now i could export a mp4 video and it looks alright.
only a run preview window shows that flicker.

Now i installed a new graphic driver, but now my taskbar is broken...

**Comment by morpho-matters** [comment] 2022-11-17 17:32
Glad it's resolved! I'll go ahead and close the issue then.

To your follow up question: The `j` is Python's way of referring to the imaginary unit i, the square root of -1. Pretty much all 2D positional data in Morpho is expressed as a complex number `x + y*1j`, where the real part corresponds to the x-coordinate, and the imaginary part corresponds to the y-coordinate. For example, the point (3, 4) would be specified in Morpho as `3+4j` or `complex(3,4)`. So in your example, `31j` and `-51j` refer to the positions (0, 31) and (0, -51) respectively. This is explained a little more near the beginning of the [first guide](https://morpho-matters.github.io/morpholib/guides/basic-guide).

**Closed by morpho-matters** 2022-11-17 17:32 UTC

**Comment by Drachenbauer** [comment] 2023-01-13 22:38
Yesterday there came an update for windows 11, that changed the taskbar and other things really much
And it looks like the intel graphic driver update:
[https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html](https://www.intel.com/content/www/us/en/download/19344/intel-graphics-windows-dch-drivers.html)
is no longer compatible and broke my taskbar and windows settings app.
How can i now fix the issue again

**Comment by morpho-matters** [comment] 2023-01-22 00:44
I don't know. That issue seems more to do with Windows and graphics drivers in general, and less to do with Morpho directly, so I would advise searching elsewhere for a solution or posting this issue in a different forum.
